// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFqO6Su5LEk69oQxikiPd4YjTX3nueXU',
    appId: '1:129456935260:web:2230040e2dfa10335c3199',
    messagingSenderId: '129456935260',
    projectId: 'monitus-emergency-system',
    authDomain: 'monitus-emergency-system.firebaseapp.com',
    storageBucket: 'monitus-emergency-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YbyJ2NQKeW2byE2ZJcnZGdxm-6FCV8I',
    appId: '1:129456935260:android:aad462e29f5b4bf95c3199',
    messagingSenderId: '129456935260',
    projectId: 'monitus-emergency-system',
    storageBucket: 'monitus-emergency-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNm0zmXYOELfhaqxclkOmjXjUfNAmeS0',
    appId: '1:129456935260:ios:d25b7a509f2141615c3199',
    messagingSenderId: '129456935260',
    projectId: 'monitus-emergency-system',
    storageBucket: 'monitus-emergency-system.firebasestorage.app',
    iosBundleId: 'com.example.monitusMobileClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNm0zmXYOELfhaqxclkOmjXjUfNAmeS0',
    appId: '1:129456935260:ios:d25b7a509f2141615c3199',
    messagingSenderId: '129456935260',
    projectId: 'monitus-emergency-system',
    storageBucket: 'monitus-emergency-system.firebasestorage.app',
    iosBundleId: 'com.example.monitusMobileClient',
  );

}